### ISSUE TITLE
Реализовать обновление информации о текущей итерации с временным интервалом

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#42]
Как было сказано в #39 
> Кроме усыпления рабочего потока, что, на мой взгляд, есть искусственное ограничение на скорость работы солвера, мне видится ещё одно решение: вызывать UpdateIterationInfo() в рабочем потоке по таймеру, скажем раз в 5-10 мс (UPD: реализовал в 093b3ac).

Собственно это нужно реализовать в ветке diffusion-solver-ui и не лазить в код солвера. К тому же теперь он ничего не знает о потоках.

**Comment by antonlarin** [comment]
093b3ac была тестовая версия, показать, как оно работает. Я удалю эту ветку.

**Comment by RuslanIsrafilov** [comment]
Вообще работает оно хорошо.

**Comment by antonlarin** [comment]
Раз уж играем по-взрослому, то вот, реализация в этом пулл реквесте: #43.

**Comment by RuslanIsrafilov** [comment]
@antonlarin я понял почему всё замирает в конце. Вызывается поиск минимума и максимума в слоях, он работает слишком долго, нужно оптимизировать этот момент в core.

**Comment by RuslanIsrafilov** [comment]
Считаю, что реализовано, последние изменения в fbefb26a2c26fa9062b527a5870283a54594bae9.
