### ISSUE TITLE
Падение приложения при повторном начале счёта

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#44]
Возникла следующая проблема. Выставляю количество итераций равное 500000 - всё решается. Ничего не меняю, решаю заново - падение в самом начале счёта.

**Comment by antonlarin** [comment]
Я проверил на своих компьютерах, падает под Windows, в 101 строке ```SchemeGrid.cpp``` бросается исключение, судя по всему bad_alloc, потому что в этой строке используется ```new```. Стоит заметить, что на компьютере с Windows у меня 2 ГБ памяти, а полмиллиона слоёв съедают 1 ГБ. Под Fedora не падает, но там 4 ГБ памяти.

@RuslanIsrafilov проверь ещё у себя под Ubuntu, чтобы исключить зависимость этой ошибки от платформы.

**Comment by antonlarin** [comment]
@RuslanIsrafilov у тебя ещё есть эта проблема?
@sovrasov, @DanPrj  посмотрите у себя тоже, если не трудно.

**Comment by RuslanIsrafilov** [comment]
Под Ubuntu я ещё не проверял, у меня там Qt не стоят. Прикол в том, что под Linux x64 по умолчанию компилится как x64, под Windows всегда как x86.

**Comment by antonlarin** [comment]
@RuslanIsrafilov ты думаешь, что из-за этого у меня под Linux не наблюдается проблемы?

**Comment by RuslanIsrafilov** [comment]
Да, мне кажется, что из-за этого.

**Comment by antonlarin** [comment]
Собрал 32-разрядную версия под Linux, всё работает. Так что скорее всего дело не в этом.

**Comment by RuslanIsrafilov** [comment]
А сколько памяти съедает?

**Comment by antonlarin** [comment]
~840 МБ в конце первого расчёта, до ~1600 МБ в течение второго, когда он заканчивается - опять падает до ~840 МБ.

**Comment by RuslanIsrafilov** [comment]
А сколько всего оперативки?

**Comment by antonlarin** [comment]
Под Linux 4 ГБ.

**Comment by RuslanIsrafilov** [comment]
Под Windows у тебя 2 ГБ, версия 32 бита. Windows под 32 битные программы не даёт больше половины памяти из доступной, т.е. максимум, который может быть выделен под процесс в нашем случае - 1 ГБ. 

> до ~1600 МБ в течение второго

Всё логично, под Windows должно падать.

> Собрал 32-разрядную версия под Linux, всё работает. Так что скорее всего дело не в этом.

Linux ведёт себя иначе - в нашем случае может быть выделена вся доступная память - 4 ГБ под 32-битный процесс (больше чем 4 ГБ, разумеется, под 32-битный процесс выделить нельзя).

**Comment by antonlarin** [comment]
Так будем что-нибудь с этим делать?

**Comment by RuslanIsrafilov** [comment]
Не сейчас, пока это не слишком критично.

**Comment by RuslanIsrafilov** [comment]
Ну хотя бы нужно обрабатывать это исключение на данном этапе. Может быть в феврале сделаем оптимизацию по использованию памяти.
