### ISSUE TITLE
Обновления графика во время счёта

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#45]
Из названия понятно в чём заключается эта фича.

**Comment by RuslanIsrafilov** [comment]
Ещё необходимо обновлять масштаб графика.

**Comment by antonlarin** [comment]
Ты имеешь в виду в ходе расчёта?

**Comment by RuslanIsrafilov** [comment]
Да.

**Comment by antonlarin** [comment]
Если что, я реализовал. Устраивает с точки зрения работы?

**Comment by RuslanIsrafilov** [comment]
Ты мой бог.
