### ISSUE TITLE
Неверный минимум слоя в счёте на установление

### ISSUE THREAD

**Issue by antonlarin** [antonlarin/aNiMated-batman#47]
Считаю явной схемой на установление с параметрами по умолчанию, кроме следующих:
* ε активатора и ε ингибитора - 1e-7;
* максимальное число шагов 1e7.

В этом случае минимум по активатору и по ингибитору почему-то 0.5, хотя максимум ~4.14, а функция почти константа.

**Comment by RuslanIsrafilov** [comment]
Теперь минимум и максимум в обоих режимах счёта берётся от всех слоёв полученных в процессе счёта. Раньше в режиме счёта на установление минимум и максимум считался только на последнем слое. Вот этот коммит 267f90ffa495327268f5c015fec7e4729367a531.

**Comment by antonlarin** [comment]
Для чего так было сделано?

**Comment by RuslanIsrafilov** [comment]
Я подумал, что методы подсчёта минимума и максимума в классе `SchemeSolution` должны иметь одинаковый смысл - получение минимума и максимума за всё время счёта.

**Comment by antonlarin** [comment]
Эти методы нужны для чего-то кроме масштабирования графиков? Они используются где-нибудь в core?

**Comment by RuslanIsrafilov** [comment]
Вообще-то нет. А что плохого в том, чтобы выводить последний слой на графике с *таким* масштабом, ведь при решении с сохранением всё тоже самое?

**Comment by antonlarin** [comment]
Я точно не знаю, в каком масштабе лучше показывать. Раз это не проблема, закрываю тред.
