### ISSUE TITLE
Обновлённый список требований

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#51]
Вот краткий список всех рекомендаций.

1. **Изменение в UI**
  1. ~~Переименовать "Число узлов"  в "Число разбиений".~~
  2. ~~Изменить обозначения коэффициентов задачи на греческие буквы.~~
  3. ~~Возможно добавить справку с описанием того, что каждый коэффициент значит.~~
  4. ~~Изменить кнопки "Конечный счёт" и "Бесконечный счёт" на что-то более понятное.~~
  5. ~~Необходимо сообщать о некорректности начальных условий в диалоге, в котором эти условия задаются.~~
  6. ~~Рисовать графики концентрации ингибитора и активатора различными цветами.~~
  7. Добавить возможность ручного изменения масштаба графика.
  8. ~~Добавить индикатор работы решателя, показывать окошко, в которое выводить прогресс, т.е. сколько итераций сделано из максимально возможного количества.~~
  9. Выводить более подробную информацию при завершении расчётов (по образцу "синей" программы).
    1. ~~Норму разности двух последних слоёв.~~
    2. ~~Количество сделанных итераций.~~
    3. Номер слоя на котором была достигнута требуемая точность.
    4. ~~Выводить время которое соответствует выбранному слою.~~
2. **Рекомендации по алгоритму**
  1. ~~Изменить условия остановки метода: необходимо задавать два числа (требуемую точность решения задачи), отдельно для концентрации ингибитора и активатора.~~
  2. Написать "нормальные" тесты для алгоритма.
3. **Новый функционал**
  1. ~~Добавить возможность приостановки счёта, т.е. должна присутствовать возможность остановки процесса счёта, вывод промежуточных результатов, при этом можно продолжить счёт при тех же параметрах начиная уже с последнего просчитанного слоя.~~
  2. ~~Добавить возможность изменения некоторых параметров метода в момент приостановки счёта (необходимо обсудить набор этих параметров)~~
  3. ~~Добавить возможность просматривать графики начальных условий.~~
  4. Добавить функцию ведения журнала. Пользователь должен иметь возможность сохранять результаты расчётов и параметры, при которых эти результаты получены. Пользователь должен иметь возможность просматривать все свои сохранённые результаты.
  5. Пользователь должен иметь возможность сохранять результаты и параметры текущих вычислений в файл, а после этого иметь возможность открыть этот файл и загрузить результаты расчётов и параметры в программу.
  6. ~~Возможность сохранять графики в виде картинок.~~

**Comment by RuslanIsrafilov** [comment]
Параметры, при которых системы выходит на стационарный режим
![Параметры](http://i62.tinypic.com/oucqvq.png)

**Comment by sovrasov** [comment]
Причем, этот режим неоднородный по пространству. В этом единственная их ценность.

**Comment by sovrasov** [comment]
В прошлый раз я ошибся при вводе этих параметров и запускал расчет с gamma=1. Сегодня посчитал с gamma=2 - там на самом деле периодический неоднородный по пространству режим.

<script src="https://gist.github.com/sovrasov/53faf0643e75b8ca1dfd.js"></script>

**Comment by antonlarin** [comment]
Удачная ошибка. :smiley:

**Comment by sovrasov** [comment]
Вот xml с параметрами:

`<?xml version="1.0" encoding="UTF-8"?>
<dssettings>
   <lambda1 value="0.011257909"/>
   <lambda2 value="0.909456818"/>
   <K value="3"/>
   <C value="1"/>
   <Rho value="1"/>
   <Nu value="1"/>
   <Gamma value="2"/>
</dssettings>`
