### ISSUE TITLE
Задания попроще на 6 апреля

### ISSUE THREAD

**Issue by antonlarin** [antonlarin/aNiMated-batman#55]
1. 31 марта - 7 апреля сдаём программу по уравнению диффузии. Причём, сдавать нужно не только саму программу, но и исследование системы уравнений в ней.

2. По задаче Коши для ОДУ есть задания из свежевыданной синей методички:
    * стр. 6, №1 - каждый по 1-ому пункту;
    * стр. 6, №2 - каждый по 1-ому пункту;
    * стр. 6, №3 - каждый по 1-ому методу из (2)-(6) со стр. 43;
    * стр. 7, №4 - каждый по 1-ому пункту (каждый пункт достанется двоим);
    * стр. 7, №5 - каждый по 1-ому пункту (каждый пункт достанется двоим);
    * стр. 7, №8 - каждый по 1-ому методу из (2)-(4) со стр. 43.
    * стр. 51 - там всего 8 заданий, каждый берёт себе одну пару из: (1, 8), (2, 7), (3, 6), (4, 5).

3. Ещё ожидаются задания по численному интегрированию, методу наименьших квадратов и вариационно-проекционному методу решения краевых задач, stay tuned.

**Comment by sovrasov** [comment]
стр. 6, №1 а
стр. 6, №2 б
стр. 6, №3 метод 5
стр. 7, №4 б
стр. 7, №5 а
стр. 7, №8 метод 3
стр. 51 (1, 8)

**Comment by DanPrj** [comment]
стр. 6, №1 в
стр. 6, №2 в
стр. 6, №3 метод 4
стр. 7, №4 б
стр. 7, №5 б
стр. 7, №8 метод 4
стр. 51 (3, 6)

**Comment by antonlarin** [comment]
**UPD:** пришли новые задания по МНК и вариационно-проекционному методу. В "МР" указано, как их делить, поэтому как только кто-то определился, что хочет делать нечто, пишите № практикума, задачи и варианта, если задача с вариантом.

[Практикум 4](https://drive.google.com/file/d/0B_Oepge5gZN3ZURneTlWT3VVN2c/view?usp=sharing)
[Практикум 5](https://drive.google.com/file/d/0B_Oepge5gZN3ZXk1Z1FtTHZlMnc/view?usp=sharing)

**Comment by antonlarin** [comment]
стр. 6, №1 г
стр. 6, №2 а
стр. 6, №3 метод 6
стр. 7, №4 а
стр. 7, №5 а
стр. 7, №8 метод 3
стр. 51 (2, 7)

**Comment by RuslanIsrafilov** [comment]
**Задача Коши**
стр. 6, №1 б
стр. 6, №2 а
стр. 6, №3 метод 3
стр. 7, №4 а
стр. 7, №5 б
стр. 7, №8 метод 4
стр. 51 (4, 5)

**Практикум 4**
№1 - 2
№2 - 2
№3 - 4
№4 - 1
№6 - 1
№7 - 1
№8 - 1
№9 - 3

**Comment by sovrasov** [comment]
Практикум 4
#1 1
#2 1
#3 2
#4 4
#6 2
#7 2
#8 2
#9 1

**Comment by DanPrj** [comment]
Практикум 4
№1 4
№2 1
№3 1
№4 2
№6 1
№7 3
№8 2
№9 2

**Comment by sovrasov** [comment]
Практикум 5
задача 1

**Comment by antonlarin** [comment]
В 5-ом практикуме задача 1.

**Comment by RuslanIsrafilov** [comment]
Практикум 5
задача 2

**Comment by DanPrj** [comment]
Как поделим задачи из 5-го практикума, где одно решение на подгруппу? (№5, 6, 7)

**Comment by antonlarin** [comment]
Я не умею решать методами конечных элементов и Ритца.

**Comment by DanPrj** [comment]
Я попробую решить №5 из 5-го практикума

**Comment by antonlarin** [comment]
Как хочешь, но насколько мне известно, их не требуется решать.
