### ISSUE TITLE
Задания с программированием на 6 апреля

### ISSUE THREAD

**Issue by antonlarin** [antonlarin/aNiMated-batman#56]
По задаче Коши для ОДУ также нужно написать 4 программы:
* стр. 7, №9 - вариант 4 на стр. 53;
* стр. 8, №10 - вариант 4;
* стр. 8, №11 - вариант 4 на стр. 56;
* задача с двумя осцилляторами (подробности позже).

Методы нужно использовать 3 или 4 порядка, с контролем локальной погрешности (на стр. 16 есть информация про параметры контроля).
Пожелания к программам: возможность включить/выключить выход на границу, пауза и возобновление счёта (в том числе с изменёнными параметрами), построение нескольких траекторий на одной картинке и ручная очистка её.

Также нужно сделать отчёт на 1-2 страницы по схеме: постановка задачи, численный метод, что ищем, что нашли (желательно нечто интересное).

У нас коммуникация в группе не очень хорошо налажена, поэтому я думаю, что лучше каждому взять одну из этих задач.

**Comment by antonlarin** [comment]
**UPD:** [Подробности про задачу с осцилляторами](https://drive.google.com/file/d/0B_Oepge5gZN3QVEzVnAta2h4TG8/view?usp=sharing)

**Comment by RuslanIsrafilov** [comment]
стр. 8, №11 - вариант 4 на стр. 56

**Comment by DanPrj** [comment]
стр. 8, №10 - вариант 4

**Comment by RuslanIsrafilov** [comment]
Я так понимаю, что это задание все сдали.

**Comment by antonlarin** [comment]
Не совсем все, но смысле в теме всё равно больше нет.
