### ISSUE TITLE
Выводить в конце счёта время последнего слоя

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#58]
Выводить в конце счёта время, которое соответствует последнему слою.

**Comment by antonlarin** [comment]
Насколько это возможно при текущей реализации `SchemeResultsStorage` (я имею в виду двойное сохранение конечного в предыдущем запуске слоя), сделано в af1cd05d72f3dff165f0e58c0b71143d69a1fbba.
