### ISSUE TITLE
Изменения в UI для выбора режима счёта

### ISSUE THREAD

**Issue by RuslanIsrafilov** [antonlarin/aNiMated-batman#59]
Предлагаю выбирать режимы "Счёт на установление" и "Вычисление всех слоёв" с помощью Radio Button. Добавить кнопки "Запустить счёт заново" и "Продолжить счёт".

**Comment by antonlarin** [comment]
Только в свете новой функциональности возможно стоит переименовать опцию "Вычисление всех слоёв".

**Comment by antonlarin** [comment]
@RuslanIsrafilov нормально сделал, или что-то нужно изменить?

**Comment by RuslanIsrafilov** [comment]
Божественно.
