### ISSUE TITLE
Долгая пауза перед диалогом с результатом расчёта

### ISSUE THREAD

**Issue by antonlarin** [antonlarin/aNiMated-batman#60]
Если оставить начальные параметры как есть и поставить 2000000 шагов, то после завершения расчёта некоторое время висит диалог прогресса, и потом он меняется на диалог с результатами. Нужна помощь с отладкой.

**Comment by antonlarin** [comment]
Окей, скорее всего у меня просто работа со свопом происходит.

**Comment by sovrasov** [comment]
У меня все вообще упало с таким числом слоев. Причем не сразу, а где-то после половины итераций. Сначала появился пустой messageBox, потом сообщение windows, что программа остановлена. Собирал под x86.
Ты шаг сохранения единичный брал?

**Comment by antonlarin** [comment]
Да, единичный.

Странно, что она падает посередине счёта, ведь, насколько я понимаю, в середине счёта не производится выделений памяти.

**Comment by RuslanIsrafilov** [comment]
Я сделал динамическое выделение памяти во время счета, поскольку есть вероятность, что счет будет остановлен и в действительности выделять память под все соли не нужно. Причины такого поведения программы возможно кроются в копировании промежуточных данных во время построения результата. Я посмотрю, по возможности оптимизирую. По мимо этого требуется корректная обработка badalloc'ов.
