### ISSUE TITLE
Теоретический вопрос по линейной алгебре

### ISSUE THREAD

**Issue by antonlarin** [antonlarin/aNiMated-batman#61]
Каждый из команды готовит конспект теоретического материала по итерационному методу с доказательством сходимости. Методы те, что рассматривали на последних лекциях:
- простой итерации;
- минимальных невязок;
- простой итерации с Чебышёвским набором параметров;
- сопряжённых градиентов.

Далее ссылки на якобы полезные материалы:
- [Общая информация](https://drive.google.com/file/d/0B_Oepge5gZN3eGlyaEpDSFZXVlE/view?usp=sharing)
- [Методы простой итерации и минимальных невязок](https://drive.google.com/file/d/0B_Oepge5gZN3MnVCakplcVhWMlU/view?usp=sharing)
- [МПИ с Чебышёвскими параметрами](https://drive.google.com/file/d/0B_Oepge5gZN3N2Itc3MyWlVKRFk/view?usp=sharing)
- [Метод сопряжённых градиентов](https://drive.google.com/file/d/0B_Oepge5gZN3eEQ2OTRPWjBvYVE/view?usp=sharing)

Выбирайте понравившийся метод и пишите об этом в комментариях.

**Comment by RuslanIsrafilov** [comment]
Минимальные невязки.

**Comment by sovrasov** [comment]
Метод сопряженных градиентов.

**Comment by DanPrj** [comment]
Простой итерации
